union AcceptInvitationResponse = Invitation | InvitationNotFound

union AddChannelResponse = Channel | ChannelNameExists | ChannelNameTooShort | ChannelNameTooLong | NoPermissions

union AddMessageResponse = Message | MessageTooLong | MessageEmpty | NoPermissions

union AddServerResponse = Server | ServerNameTooLong | ServerNameTooShort

type AuthPayload {
  token: String!
  user: User!
}

union ChangeChannelNameResponse = Channel | ChannelNameTooLong | ChannelNameTooShort | ChannelNameExists | ChannelNotFound | NoPermissions

union ChangeMemberRoleResponse = Member | MemberNotFound | NoPermissions

union ChangePasswordResponse = User | UserNotFound | InvalidPassword | PasswordTooShort

union ChangeServerNameResponse = Server | ServerNotFound | ServerNameTooLong | ServerNameTooShort | NoPermissions

type Channel {
  id: ID!
  serverId: Int!
  name: String!
  createdAt: Int!
  server: Server!
  messages(limit: Int! = 100, offset: Int! = 0): [Message!]!
}

type ChannelNameExists implements Error {
  message: String!
}

type ChannelNameTooLong implements Error {
  message: String!
}

type ChannelNameTooShort implements Error {
  message: String!
}

type ChannelNotFound implements Error {
  message: String!
}

type ContentTooLong implements Error {
  message: String!
}

union DeclineInvitationResponse = Invitation | InvitationNotFound

union DeleteChannelResponse = Channel | ChannelNotFound | NoPermissions

union DeleteMemberResponse = Member | MemberNotFound | NoPermissions

union DeleteServerResponse = Server | ServerNotFound | NoPermissions

union DeleteUserResponse = User | UserNotFound

type EmailExists implements Error {
  message: String!
}

interface Error {
  message: String!
}

union GetChannelResponse = Channel | ChannelNotFound | NoPermissions

union GetMemberResponse = Member | MemberNotFound | NoPermissions

union GetMessageResponse = Message | MessageNotFound | NoPermissions

union GetServerResponse = Server | ServerNotFound | NoPermissions

union GetUserResponse = User | UserNotFound

type InvalidLoginData implements Error {
  message: String!
}

type InvalidPassword implements Error {
  message: String!
}

type Invitation {
  serverId: Int!
  userId: Int!
  content: String
  createdAt: Int!
  server: Server!
  user: User
}

type InvitationExists implements Error {
  message: String!
}

type InvitationNotFound implements Error {
  message: String!
}

union InviteUserResponse = Invitation | ContentTooLong | MemberExists | InvitationExists | UserNotFound | NoPermissions

union LoginResponse = AuthPayload | InvalidLoginData

type Member {
  id: ID!
  name: String!
  email: String!
  createdAt: Int!
  servers: [Server!]!
  serverId: Int!
  role: Role!
  joinedAt: Int!
  server: Server!
}

type MemberExists implements Error {
  message: String!
}

type MemberNotFound implements Error {
  message: String!
}

type Message {
  id: ID!
  serverId: Int!
  channelId: Int!
  authorId: Int!
  content: String!
  createdAt: Int!
  author: Member
  channel: Channel!
  server: Server!
}

type MessageEmpty implements Error {
  message: String!
}

type MessageNotFound implements Error {
  message: String!
}

type MessageTooLong implements Error {
  message: String!
}

type Mutation {
  addServer(name: String!): AddServerResponse!
  changeServerName(serverId: Int!, newName: String!): ChangeServerNameResponse!
  deleteServer(serverId: Int!): DeleteServerResponse!
  addChannel(serverId: Int!, name: String!): AddChannelResponse!
  changeMemberRole(serverId: Int!, userId: Int!, newRole: Role!): ChangeMemberRoleResponse!
  kickMember(serverId: Int!, userId: Int!): DeleteMemberResponse!
  leaveServer(serverId: Int!): DeleteMemberResponse!
  changeChannelName(serverId: Int!, channelId: Int!, newName: String!): ChangeChannelNameResponse!
  deleteChannel(serverId: Int!, channelId: Int!): DeleteChannelResponse!
  register(username: String!, password: String!, email: String!): RegisterResponse!
  login(username: String!, password: String!): LoginResponse!
  changePassword(oldPassword: String!, newPassword: String!): ChangePasswordResponse!
  deleteUser: DeleteUserResponse!
  addMessage(serverId: Int!, channelId: Int!, content: String!): AddMessageResponse!
  inviteUser(serverId: Int!, userId: Int!, content: String!): InviteUserResponse!
  acceptInvitation(serverId: Int!): AcceptInvitationResponse!
  declineInvitation(serverId: Int!): DeclineInvitationResponse!
}

type NoPermissions implements Error {
  message: String!
}

type PasswordTooShort implements Error {
  message: String!
}

type Query {
  server(serverId: Int!): GetServerResponse!
  channel(serverId: Int!, channelId: Int!): GetChannelResponse!
  firstChannel(serverId: Int!): GetChannelResponse!
  message(serverId: Int!, channelId: Int!, messageId: Int!): GetMessageResponse!
  messages(serverId: Int!, channelId: Int!, limit: Int! = 100, offset: Int! = 0): [Message!]!
  member(serverId: Int!, userId: Int!): GetMemberResponse!
  invitations: [Invitation!]!
  currentUser: GetUserResponse!
  user(username: String!): GetUserResponse!
}

union RegisterResponse = AuthPayload | UserNameExists | EmailExists | PasswordTooShort

enum Role {
  OWNER
  MODERATOR
  MEMBER
}

type Server {
  id: ID!
  name: String!
  createdAt: Int!
  channels: [Channel!]!
  members: [Member!]!
}

type ServerNameTooLong implements Error {
  message: String!
}

type ServerNameTooShort implements Error {
  message: String!
}

type ServerNotFound implements Error {
  message: String!
}

type Subscription {
  newMessage(serverId: Int!, channelId: Int!): Message!
  newMember(serverId: Int!): Member!
  newChannel(serverId: Int!): Channel!
  newInvitation: Invitation!
  updatedServerName(serverId: Int!): Server!
  updatedChannelName(serverId: Int!): Channel!
  deletedServer(serverId: Int!): Server!
  deletedChannel(serverId: Int!): Channel!
  deletedMember(serverId: Int!): Member!
}

type User {
  id: ID!
  name: String!
  email: String!
  createdAt: Int!
  servers: [Server!]!
}

type UserNameExists implements Error {
  message: String!
}

type UserNotFound implements Error {
  message: String!
}
